name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # 触发工作流的分支
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build-and-push:
    runs-on: ubuntu-22.04-arm  # 使用 ARM 架构的 Ubuntu 22.04 镜像

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 克隆当前仓库

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # 设置 Docker Buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub 用户名
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub 密码

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./Tool-Solutions/ML-Frameworks/pytorch-aarch64  # Docker 构建上下文路径
          file: ./Tool-Solutions/ML-Frameworks/pytorch-aarch64/Dockerfile  # Dockerfile 路径
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pytorch:arm  # 目标镜像标签
