name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # 触发工作流的分支
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build-and-push:
    runs-on: ubuntu-22.04-arm  # 使用 ARM 架构的 Ubuntu 22.04 镜像

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3  # 克隆当前仓库

      - name: Clone ARM-software/Tool-Solutions repository
        run: |
          git clone https://github.com/ARM-software/Tool-Solutions.git

      - name: Run build.sh script
        run: |
          cd Tool-Solutions/ML-Frameworks/pytorch-aarch64
          ./build.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # 设置 Docker Buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub 用户名
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub 密码

      - name: Tag Docker image
        run: |
          docker tag toolsolutions-pytorch:latest ${{ secrets.DOCKER_USERNAME }}/pytorch:arm

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/pytorch:arm
